# Generated by Django 5.2.1 on 2025-06-03 21:22

import django.db.models.deletion
import django.utils.timezone
import listings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('SINGLE_ROOM', 'Одна комната (студия)'), ('ONE_BEDROOM', 'Одна комната с отдельной спальней'), ('TWO_BEDROOM', 'Две комнаты с общей ванной'), ('TWO_BEDROOM_ENSUITE', 'Две комнаты с отдельными ванными'), ('THREE_BEDROOM', 'Три комнаты'), ('SUITE', 'Сьют / Апартаменты'), ('SHARED_ROOM', 'Общая комната / койко-место'), ('PRIVATE_ROOM_IN_SHARED', 'Отдельная комната в общей квартире'), ('LOFT', 'Лофт / Мансарда'), ('STUDIO', 'Студия'), ('HAUS', 'Дом')], default=listings.models.RoomType['SINGLE_ROOM'], max_length=36),
        ),
        migrations.AddField(
            model_name='listing',
            name='rooms_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
